### ISSUE TITLE
Need help in solving Kamisado

### ISSUE THREAD

**Issue by imsoumen** [Chadys/Kamisado#11]
Hey Chadys,

Hope you and your family are doing good.

I was going through your code you wrote for Kamisado game. I was trying to use your logic for one hackerrank problem. I am struggling in it.

Can you please help me solve the below problem:
https://www.hackerrank.com/challenges/kamisado/problem

git Issue I have created to contact you.

Regards,
Soumen

**Comment by Chadys** [comment]
Hello, I'm sorry but I don't really have the time to tutor anyone. Issues are not meant to be used because you want help solving an hackerrank problem, for that use stackoverflow or such (and you should give a more detailed description of what you are struggling with instead of just saying "I can't solve it plz help", you won't get any answer this way). My code was made to run for a specific representation and communication protocol. To follow the hackerrank specifications you'll probably need to rewrite a lot of the core logic. I used a mcts algorithm as a solver, you can find a lot of resources explaining how it works on the web. For the rest I think the readme of the project is pretty explicit. It's a simple school project I made years ago, not something I'm expecting to work on again.
Good day, closing this
